services:
  python-api:
    container_name: python-api
    image: python-api
    build:
      context: ./python-api
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - TZ=UTC
    ports:
      - "8001:8001"
    hostname: python-api
    volumes:
      - ./volumes/logs:/app/python-api/logs/python-api.logs
    networks:
      - mongodb-net
    depends_on:
      - mongodb
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
    restart: always
    profiles:
      - api

  monitor-api:
    container_name: monitor-api
    image: monitor-api
    build:
      context: ./monitor-api
    volumes:
      - ./volumes/logs:/opt/monitor/logs
    environment:
      - TARGET_CONTAINER_HOST=python-api
      - TARGET_CONTAINER_PORT=8001
      - CHECK_INTERVAL=5
      - TZ=America/Bogota
    ports:
      - "8002:8002"
    hostname: monitor-api
    networks:
      - mongodb-net
    depends_on:
      - python-api
    restart: always
    profiles:
      - monitor

  mongodb:
    container_name: mongodb
    image: mongo:latest
    networks:
      - mongodb-net
    ports:
       - "27017:27017"
    hostname: mongodb
    volumes:
      - mongodb-data:/data/db
    restart: always
    profiles:
      - db

networks:
  mongodb-net:
    driver: bridge
    name: mongodb-net

volumes:
  mongodb-data:
    name: mongodb-data
