version: '3.8'
services:
  api:
    build: . # Construye la imagen desde el Dockerfile actual
    container_name: python_api
    env_file:
      - ./.env # Carga las variables de entorno desde .env
    ports:
      - "8001:8001" # Expone el puerto de la API
    volumes:
      - ./logs:/opt/python-api/logs
    networks:
      - mongodb-net # Conectar a la red de MongoDB
    depends_on:
      - mongodb
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]

  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - mongodb-net # Conectar a la red de MongoDB
    ports:
      - "27017:27017" # Expone el puerto de MongoDB

networks:
  mongodb-net:
    driver: bridge # Conecta los servicios (api y mongoDB) a la misma red