version: '3.8'

services:
  python-api:
    container_name: python_api # Nombre del contenedor
    build: . # Construye imagen desde Dockerfile actual
    #env_file:
    #  - ./.env # Carga variables de entorno desde .env
    environment:
      - MONGODB_HOST
      - MONGODB_PORT
      - TZ
    ports:
      - "8001:8001" # Expone puerto de API
    hostname: python-api
    volumes:
      - ./volumes/logs:/opt/python-api/logs/api_info.logs
    networks:
      - mongodb-net # Conectar a red de MongoDB
    depends_on:
      - mongodb
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
    restart: always
    profiles:
      - api

  mongodb:
    container_name: mongodb
    image: mongo:latest
    networks:
      - mongodb-net
    ports:
       - "27017:27017"
    hostname: mongodb
    volumes:
      - mongodb-data:/data/db
    restart: always
    profiles:
      - db

networks:
  mongodb-net:
    driver: bridge
    name: mongodb-net

volumes:
  mongodb_data:
    name: mongodb-data