services:
  python-api:
    container_name: python-api # Nombre del contenedor
    build:
      context: ./python-api # Construye la imagen desde la carpeta python-api
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - TZ=UTC
    ports:
      - "8001:8001" # Expone puerto de API
    hostname: python-api
    volumes:
      - ./volumes/logs:/app/python-api/logs/python-api.logs # Ajuste del volumen para logs
    networks:
      - mongodb-net # Conectar a red de MongoDB
    depends_on:
      - mongodb
    entrypoint: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
    restart: always
    profiles:
      - api

  monitor-api:
    container_name: monitor-api
    build:
      context: ./monitor-api
    volumes:
      - ./volumes/logs:/opt/monitor/logs
    environment:
      - TARGET_CONTAINER_HOST=python-api
      - TARGET_CONTAINER_PORT=8001
      - CHECK_INTERVAL=5
      - TZ=America/Bogota
    networks:
      - mongodb-net
    depends_on:
      - python-api
    restart: always
    profiles:
      - monitor-api

  mongodb:
    container_name: mongodb
    image: mongo:latest
    networks:
      - mongodb-net
    ports:
       - "27017:27017" # Puerto para MongoDB
    hostname: mongodb
    volumes:
      - mongodb-data:/data/db # Volumen persistente para MongoDB
    restart: always
    profiles:
      - db

networks:
  mongodb-net:
    driver: bridge
    name: mongodb-net

volumes:
  mongodb-data:
    name: mongodb-data
